---
# Playbook to setup OCP4 install host

- name: Deploy CLI utilities for deploying Red Hat OpenShift
  hosts: localhost
  become: True

  tasks:

    # Setup temp and working directory

    - name: Get current_working_directory
      shell: pwd
      register: current_working_directory
      tags:
        - always

    - name: Generate temp directory in working directory
      file:
        path: "{{ current_working_directory.stdout }}/temp"
        state: directory
      register: temp_dir
      tags:
        - always
    
    - name: Print temp dir location
      debug:
        msg: "The temp directory is {{ temp_dir.path }}"
      tags:
        - always


    # Deploy AWS ClI v2 utility 
    - name: Download the latest AWS Command Line Interface
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: "{{ temp_dir.path }}/awscliv2.zip"
      tags:
        - aws_cli

    - name: Unzip archive with unarchive module
      unarchive:
        src: "{{ temp_dir.path }}/awscliv2.zip"
        dest: "{{ temp_dir.path }}"
      tags:
        - aws_cli

    - name: Install the AWS CLI into /bin/aws
      command:
      args:
        chdir: "{{ temp_dir.path }}"
        cmd: "{{ item }}"
      with_items:
        - "aws/install --update"
      tags:
        - aws_cli


    # Openshift oc command
    - name: Download the latest oc command
      get_url: 
        url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz"
        dest: "{{ temp_dir.path }}/openshift-client-linux.tar.gz"
      tags:
        - oc_client

    - name: Install oc into /usr/local/bin
      unarchive:
        src: "{{ temp_dir.path }}/openshift-client-linux.tar.gz"
        dest: "/usr/local/bin"
      tags:
        - oc_client

    - name: Remove oc tar and readme file
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/usr/local/bin/README.md"
        - "{{ temp_dir.path }}/openshift-client-linux.tar.gz"
      tags:
        - oc_client

    # Openshift Installer
    - name: Download the latest openshift-install
      get_url:
        url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-install-linux.tar.gz"
        dest: "{{ temp_dir.path }}/openshift-install-linux.tar.gz"
      tags:
        - openshift_installer

    - name: Untar openshift-install with unarchive module
      unarchive:
        src: "{{ temp_dir.path }}/openshift-install-linux.tar.gz"
        dest: "/usr/local/bin"
      tags:
        - openshift_installer
      
    - name: Remove openshift-install tar and readme file
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/usr/local/bin/README.md"
        - "{{ temp_dir.path }}/openshift-install-linux.tar.gz"
      tags:
        - openshift_installer
     
   # Helm Tool
    - name: Download and install the latest Helm tool
      get_url:
        url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/helm/latest/helm-linux-amd64"
        dest: "/usr/local/bin/helm"
        mode: "0555"
      tags:
        - helm_cli

    # Install completion scripts
    - name: Install completion scripts
      shell: "{{ item }}"
      args:
        executable: /bin/bash
      with_items:
        - "/usr/local/bin/oc completion bash > /etc/bash_completion.d/oc-completion"
        - "/usr/local/bin/openshift-install completion bash > /etc/bash_completion.d/openshift-install-completion"
        - "/usr/local/bin/helm completion bash > /etc/bash_completion.d/helm-completion"
        - "echo 'complete -C '/usr/local/bin/aws_completer' aws' >> /etc/bashrc"
      tags:
        - completion_scripts

# Post 
  post_tasks:
    - name: Remove temp directory
      file:
         path: "{{ current_working_directory.stdout }}/temp"
         state: absent
      tags: 
        - always
